apiVersion: v1
kind: Service
metadata:
  name: "go-hello-crd-controller"
  labels:
    app: "go-hello-crd-controller"
spec:
  selector:
    app: go-hello-crd-controller
  type: NodePort
  ports:
  - port: 8080
