apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: go-hello-crd-controller-virtualservice
  # namespace: hello
spec:
  hosts:
  - "*"
  gateways:
  - go-hello-crd-controller-gateway
  http:
  - match:
    - uri:
        # exact: /
        # exact: /hello
        prefix: /
        # prefix: /hello
    route:
    - destination:
        host: go-hello-crd-controller
        port:
          number: 5000
