apiVersion: v1
kind: Service
metadata:
  name: go-hello-crd-controller
  # namespace: hello
  labels:
    app: go-hello-crd-controller
spec:
  selector:
    app: go-hello-crd-controller
  ports:
  - name: http
    port: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-hello-crd-controller
  # namespace: hello
  labels:
    app: go-hello-crd-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-hello-crd-controller
  template:
    metadata:
      labels:
        app: go-hello-crd-controller
        version: v1
    spec:
      containers:
      - name: go-hello-crd-controller
        image: cclhsu/go_hello_crd_controller:latest
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent # Always | Never | IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: go-hello-crd-controller-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: go-hello-crd-controller
  # namespace: hello
spec:
  hosts:
  - "*"
  gateways:
  - go-hello-crd-controller-gateway
  http:
  - match:
    - uri:
        # exact: /
        # exact: /hello
        prefix: /
        # prefix: /hello
    route:
    - destination:
        host: go-hello-crd-controller
        port:
          number: 5000
